### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by amiltonwong** [alexlocher/hpmvs#3]
Hi, all,

After I cmake ..  ,

I got the following "STLPLUS" missing message. So I go to STLPLUS website for building step. http://stlplus.sourceforge.net/stlplus3/docs/building.html
The building steps for STLPLUS is not easy for me. Could someone give some brief steps on how to compile and install the required STLPLUS library?

Thanks~
# 

-- Could NOT find LibSTLPLUS (missing:  STLPLUS_INCLUDE_DIR STLPLUS_LIBRARY) 
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- NLOPT: Version number 2.4.2 found in configure.ac
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
STLPLUS_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /data/code/hpmvs
STLPLUS_LIBRARY (ADVANCED)
    linked by target "hpmvs" in directory /data/code/hpmvs

-- Configuring incomplete, errors occurred!
See also "/data/code/hpmvs/build/CMakeFiles/CMakeOutput.log".
See also "/data/code/hpmvs/build/CMakeFiles/CMakeError.log".
#

**Comment by pmoulon** [comment]
Building STLPLUS3 is easy.
Download:
https://sourceforge.net/projects/stlplus/files/makefiles/1.9/
https://sourceforge.net/projects/stlplus/files/stlplus3/3.13/
Put them in the same directory.
Go into stlplus3/source/, and then launch make VARIANT=release
Then just tell to hpmvs cmake where to find the build files:

```
cmake ../hpmvs 
 -DSTLPLUS_INCLUDE_DIR="pathWhereYouHaveUnZipSTLPLUS"
 -DSTLPLUS_LIBRARY="pathWhereYouHaveUnZipSTLPLUS/stlplus3/source/GNULINUX-x86_64-RELEASE/"
```

Else you can use the FORK made by Chris https://github.com/alexlocher/hpmvs/pull/2

**Comment by sweeneychris** [comment]
@pmoulon the instructions you mention above (and other similar variations) did not work for me on Linux, hence the pull request ;)

**Comment by pmoulon** [comment]
@sweeneychris FYI, I have done those instruction on Linux (tested on Linux Mint)
BTW, with the PR the user will be able to test the code more easily ;-)

**Comment by amiltonwong** [comment]
Thanks @pmoulon for your suggestion,
Using the PR from https://github.com/alexlocher/hpmvs/pull/2 save me a lot of works

**Comment by alexlocher** [comment]
I merged the pull request from @sweeneychris => thank you!
