### ISSUE TITLE
Scalability of hpmvs?

### ISSUE THREAD

**Issue by ManishSahu53** [alexlocher/hpmvs#7]
Can this algorithm scale for large number of images? eg. >1000 images

**Comment by alexlocher** [comment]
The algorithm can easiely process subcells of the complete 3d model and scales pretty well. For really large models (the ones you mention) I would recommend a bit of tweaking for efficient processing. Right now all images are loaded into the RAM at the beginning, which (depending on your hardware) is probably not feasable...

**Comment by pmoulon** [comment]
It would be nice to have a kind of LRU cache for the image.
So images would be loaded or reused on the fly at the required dimension.
